name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h "127.0.0.1" --silent; do
          echo 'waiting for mysql...'
          sleep 5
        done

    - name: Create database
      run: |
        mysql -h 127.0.0.1 -u root -psecret -e "CREATE DATABASE switcher;"

    - name: Run iterablefix.py
      run: |
        source .venv/bin/activate
        python iterablefix.py

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: secret

    - name: Cache MySQL data
      uses: actions/cache@v2
      with:
        path: /var/lib/mysql
        key: ${{ runner.os }}-mysql-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-mysql-